import Project.connectionProvider;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import org.mindrot.jbcrypt.BCrypt;

///////////////////////////////////////////
/**
 *
 * @author Moahamad Moaqaly 
 * matriculation number: 1310757
 * *************
 * @author Yousef Ghanem 
 * matriculation number: 1310760
 * *+***********
 * @author Nassim Laaraj
 * matriculation number: 1366099
 * 
 *  @author Javiel Figuereo Schade
 * matriculation number: 1324563
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LogIn() {
        initComponents();
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        studentLogin = new javax.swing.JButton();
        titleLogInAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        titleLMS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1000, 1000));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1400, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2790, -1100, 4480, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -270, -1, -1));

        JPanel1.setBackground(new java.awt.Color(48, 50, 78));
        JPanel1.setForeground(new java.awt.Color(255, 255, 255));
        JPanel1.setMinimumSize(new java.awt.Dimension(400, 827));
        JPanel1.setPreferredSize(new java.awt.Dimension(400, 1000));
        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        JPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 350, 30));

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_user_32px.png"))); // NOI18N
        usernameLabel.setText("Username");
        JPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 29));

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_password_30px.png"))); // NOI18N
        passwordLabel.setText("Password");
        JPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 150, 40));

        jPasswordField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 350, 30));

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_enter_50px_3.png"))); // NOI18N
        login.setText("Login");
        login.setPreferredSize(new java.awt.Dimension(126, 55));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        JPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 150, 50));

        exit.setBackground(new java.awt.Color(204, 0, 0));
        exit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_fire_exit_50px.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        JPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 150, 50));

        studentLogin.setBackground(new java.awt.Color(48, 50, 78));
        studentLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        studentLogin.setForeground(new java.awt.Color(255, 255, 255));
        studentLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_student_male_50px.png"))); // NOI18N
        studentLogin.setText("Login as student");
        studentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginActionPerformed(evt);
            }
        });
        JPanel1.add(studentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 240, 50));

        titleLogInAdmin.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        titleLogInAdmin.setForeground(new java.awt.Color(255, 255, 255));
        titleLogInAdmin.setText("Login as Admin");
        JPanel1.add(titleLogInAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icon_of_the_programm-removebg-preview.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        JPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, 130));

        getContentPane().add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JPanel2.setBackground(new java.awt.Color(24, 27, 52));
        JPanel2.setMinimumSize(new java.awt.Dimension(700, 700));
        JPanel2.setName(""); // NOI18N
        JPanel2.setPreferredSize(new java.awt.Dimension(1000, 1000));
        JPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(48, 50, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLMS.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        titleLMS.setForeground(new java.awt.Color(255, 255, 255));
        titleLMS.setText("Library Management System");
        jPanel3.add(titleLMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        JPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/photo_2023-02-05_14-55-43-removebg.png"))); // NOI18N
        JPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 50, -1, -1));

        getContentPane().add(JPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // button2 for close
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
      
        //to shut down when this methode is executed 
        System.exit(0);
        
    }//GEN-LAST:event_exitActionPerformed

    //button1 for login
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if (jTextField1.getText().equals("admin") && jPasswordField1.getText().equals("admin"))
        {
            //to get the next window which is home if the input is correct
            setVisible(false );
            new Home().setVisible(true);
        }
        else {
            //incorrect input
            //JOptionPane.showMessageDialog(null, "Incorrect Username or Password ");
                  
        // Connect to the database
        try  {
            Connection con = connectionProvider.getCon();
            //create a statement object
            Statement st = con.createStatement();

            // Retrieve the stored username and hashed password
            String username = jTextField1.getText();
            String password = jPasswordField1.getText();
            //Using PreparedStatement instead of Statement since it is more safe @Nassim
            String query = "SELECT hashed_password FROM lms.admins WHERE username = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();

            // Check if the entered username and hashed password match the ones stored in the database
            if (rs.next() && BCrypt.checkpw(password, rs.getString("hashed_password"))) {
                // Hide the current window and show the Home window if the input is correct
                setVisible(false);
                new Home().setVisible(true);
            } else {
                // Incorrect input
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
     }
        
     }                                     

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //Button 3 is for login as student 
    private void studentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginActionPerformed
        // Go to the student login window:
        setVisible(false);
        new StudentLogIn().setVisible(true);
        
    }//GEN-LAST:event_studentLoginActionPerformed

    private void JPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JPanel2AncestorAdded
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton login;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton studentLogin;
    private javax.swing.JLabel titleLMS;
    private javax.swing.JLabel titleLogInAdmin;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    JPanel getJPanel2() {
        return JPanel2;
    }
     JPanel getJPanel1() {
        return JPanel1;
    }
}
