

import Project.connectionProvider;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author Moahamad Moaqaly 
 * matriculation number: 1310757
 * *************
 * @author Yousef Ghanem 
 * matriculation number: 1310760
 * *+***********
 * @author Nassim Laaraj
 * matriculation number: 1366099
 * 
 *  @author Javiel Figuereo Schade
 * matriculation number: 1324563
 */
public class StudentLogIn extends javax.swing.JFrame {
    /**
     * Creates new form studentLogin
     */
    public StudentLogIn() {
        initComponents();
        //Maximize the window 
         setResizable(false);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentIdInput = new javax.swing.JTextField();
        studentIDLabel = new javax.swing.JLabel();
        studentLastNameInput = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        titleLogInStudent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        titleLMS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 50, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentIdInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(studentIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 330, 30));

        studentIDLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        studentIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentIDLabel.setText("StudentID");
        jPanel1.add(studentIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        studentLastNameInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(studentLastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 330, 30));

        lastNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last name");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 25));

        logIn.setBackground(new java.awt.Color(153, 153, 153));
        logIn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 255, 255));
        logIn.setText("Login");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        jPanel1.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 150, 50));

        goBack.setBackground(new java.awt.Color(204, 0, 0));
        goBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        goBack.setForeground(new java.awt.Color(255, 255, 255));
        goBack.setText("Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        jPanel1.add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 50));

        titleLogInStudent.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        titleLogInStudent.setForeground(new java.awt.Color(255, 255, 255));
        titleLogInStudent.setText("Login as Student");
        jPanel1.add(titleLogInStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icon_of_the_programm-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 210, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 990));

        jPanel2.setBackground(new java.awt.Color(24, 27, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(48, 50, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLMS.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        titleLMS.setForeground(new java.awt.Color(255, 255, 255));
        titleLMS.setText("Library Management System");
        jPanel3.add(titleLMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1030, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/photo_2023-02-05_14-55-43-removebg.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 990, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // button 2 for Back 
    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // Go to the main Login as admin :
        setVisible(false);
        new LogIn().setVisible(true);
        
    }//GEN-LAST:event_goBackActionPerformed

    //button1 is for login 
    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // the login button 
        
        String lastName = studentLastNameInput.getText();
        int studentID = Integer.parseInt(studentIdInput.getText());
        
        //forward the studentID to the class IssuedBook in Order to view the student's issued Book
        StudentViewBook.studentID = studentIdInput.getText();
     
        // Verify the student in the database
        
        try {
            Connection con=connectionProvider.getCon();
            Statement st=con.createStatement();
            
        String sql = "SELECT studentID FROM student WHERE lastName = '" + lastName + "' AND studentID = " + studentID;
        ResultSet rs = st.executeQuery(sql);
        if (rs.next()) {
        // Student found, log in
        JOptionPane.showMessageDialog(null, "Welcome, student " + lastName + "!", "Log in successful", JOptionPane.INFORMATION_MESSAGE);
        // Open the student home window
        new StudentHome().setVisible(true);
       
        // close connection to database
        con.close();
        // Close the current window
        JFrame currentWindow = (JFrame) SwingUtilities.getWindowAncestor(logIn);
        currentWindow.dispose();
        } else {
            // Student not found
            JOptionPane.showMessageDialog(null, "Invalid last name or student ID.", "Error", JOptionPane.WARNING_MESSAGE);
       }
    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    
        
        
        
    }//GEN-LAST:event_logInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogIn().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton logIn;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIdInput;
    private javax.swing.JTextField studentLastNameInput;
    private javax.swing.JLabel titleLMS;
    private javax.swing.JLabel titleLogInStudent;
    // End of variables declaration//GEN-END:variables
}
