
import javax.swing.JPanel;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Moahamad Moaqaly 
 * matriculation number: 1310757
 * *************
 * @author Yousef Ghanem 
 * matriculation number: 1310760
 * *+***********
 * @author Nassim Laaraj
 * matriculation number: 1366099
 * 
 *  @author Javiel Figuereo Schade
 * matriculation number: 1324563
 */
public class StudentHome extends javax.swing.JFrame {

    
    /**
     * Creates new form studentHome
     */
    public StudentHome() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studentLogout = new javax.swing.JButton();
        openCatalogue = new javax.swing.JButton();
        viewIssuedBook = new javax.swing.JButton();
        titleWelcome1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/photo_2023-02-05_14-55-43-removebg.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 50, 78));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentLogout.setBackground(new java.awt.Color(24, 27, 52));
        studentLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        studentLogout.setForeground(new java.awt.Color(255, 255, 255));
        studentLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_logout_50px.png"))); // NOI18N
        studentLogout.setText("Logout");
        studentLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(studentLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 400, 60));

        openCatalogue.setBackground(new java.awt.Color(24, 27, 52));
        openCatalogue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        openCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        openCatalogue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_literature_50px.png"))); // NOI18N
        openCatalogue.setText("Catalogue ");
        openCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCatalogueActionPerformed(evt);
            }
        });
        jPanel1.add(openCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 400, 90));

        viewIssuedBook.setBackground(new java.awt.Color(24, 27, 52));
        viewIssuedBook.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewIssuedBook.setForeground(new java.awt.Color(255, 255, 255));
        viewIssuedBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_book_reading_50px.png"))); // NOI18N
        viewIssuedBook.setText("View Issued Book(s)");
        viewIssuedBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIssuedBookActionPerformed(evt);
            }
        });
        jPanel1.add(viewIssuedBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 100));

        titleWelcome1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        titleWelcome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_user_50px_1.png"))); // NOI18N
        titleWelcome1.setText("Welcome Student !");
        jPanel1.add(titleWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icon_of_the_programm-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 170, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(24, 27, 52));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // button4 is for logout 
    private void studentLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLogoutActionPerformed
        // Return to the main login window :
        setVisible(false);
        new LogIn().setVisible(true);
        
    }//GEN-LAST:event_studentLogoutActionPerformed

    // button for catalogue 
    private void openCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCatalogueActionPerformed
        // Go to the book catalogue:
        
        StudentBookCatalogue StudentBookCatalogue1 = new StudentBookCatalogue();
        JPanel panel = StudentBookCatalogue1.getJPanel2(); // <-- get the JPanel from the NewBook class
        if(currentPanel != null){
            currentPanel.setVisible(false);
        }
        currentPanel = panel;
        jPanel2.add(panel);
        panel.setBounds(jPanel2.getBounds());
        jPanel2.revalidate();
        jPanel2.repaint();
        
        
        
    }//GEN-LAST:event_openCatalogueActionPerformed

    private void viewIssuedBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssuedBookActionPerformed
        // TODO add your handling code here:
        //new StudentViewBook().setVisible(true);
        StudentViewBook StudentViewBook1 = new StudentViewBook();
        JPanel panel = StudentViewBook1.getJPanel2(); // <-- get the JPanel from the NewBook class
        if(currentPanel != null){
            currentPanel.setVisible(false);
        }
        currentPanel = panel;
        jPanel2.add(panel);
        panel.setBounds(jPanel2.getBounds());
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_viewIssuedBookActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }
 private JPanel currentPanel = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton openCatalogue;
    private javax.swing.JButton studentLogout;
    private javax.swing.JLabel titleWelcome1;
    private javax.swing.JButton viewIssuedBook;
    // End of variables declaration//GEN-END:variables
}
